<a href="https://colab.research.google.com/github/vineeth34064/Netflix-movie-recommendation-system./blob/main/netflixmovie_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=b99937bca199df605b7659c74e004b7786c3cf6e367a0846a9532830a0a43e23
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

importing dataset

In [3]:
dataset = pd.read_csv('netflix.csv')

In [4]:
dataset

,The Lord of the rings,Cinema Paradiso,Se7en,Avengers: Infinity War,The Shining,High and Low,Terminator 2: Judgment Day,Toy Story,City of God,Witness for the Prosecution,...,Black Panther,Hamilton,The Dark Knight,Once Upon a Time in the West,The Great Dictator,Back to the Future,Aliens,Comedy nights with Kapil,Unnamed: 20,Unnamed: 21
0,The Shawshank Redemption,Fight Club,Pulp Fiction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Godfather,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,The Godfather: Part II,Se7en,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The Dark Knight,The Intouchables,One Flew Over the Cuckoo's Nest,whole wheat Star Wars: Episode V - The Empire ...,Whiplash,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12 Angry Men,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7462,Prision Break,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7463,Harry Potter 2,Whiplash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7464,Pulp Fiction,Back to the Future,Star Wars: Episode IV - A New Hope,12 Angry Men,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
transactions = dataset.iloc[:7466, :20].astype(str).values.tolist()

In [12]:
transactions #this will result in getting 2d array

[['The Shawshank Redemption',
  'Fight Club',
  'Pulp Fiction',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather: Part II',
  'Se7en',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'The Intouchables',
  "One Flew Over the Cuckoo's Nest",
  'whole wheat Star Wars: Episode V - The Empire Strikes Back',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['12 Angry Men',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Kanan Gill Comedy',
  'The Lord of the Rings: The Return of the King',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["Schindler's List",
  'Game of thrones',
  'American History X',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Billa',
  'The Lord of the Rings: The Fellowship of the Ring',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Return of the King',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Pulp Fiction',
  'Memento',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Good, the Bad and the Ugly',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather: Part II',
  'The Shawshank Redemption',
  'The Dark Knight',
  'Pulp Fiction',
  'The Departed',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Fellowship of the Ring',
  'Parasite',
  'The Good, the Bad and the Ugly',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'Once Upon a Time in the West',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the rings',
  'The Silence of the Lambs',
  'Prision Break',
  'Black Panther',
  'The Prestige',
  'The Departed',
  '12 Angry Men',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather: Part II',
  'Pulp Fiction',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather: Part II',
  'Seven Samurai',
  'The Lion King',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Dark Knight',
  'Star Wars: Episode VI - Return of the Jedi',
  'Once Upon a Time in the West',
  'Pulp Fiction',
  'Prision Break',
  'extra dark The Silence of the Lambs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Fight Club',
  'The Intouchables',
  'Black Panther',
  'The Lord of the Rings: The Return of the King',
  'The Lives of Others',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Two Towers',
  'The Lord of the rings',
  'Harry Potter 1',
  'Gladiator',
  'Pulp Fiction',
  'The Silence of the Lambs',
  'sLéon: The Professionalpoo',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Star Wars: Episode V - The Empire Strikes Back',
  'The Matrix',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Fellowship of the Ring',
  'The Dark Knight',
  'Léon: The Professional',
  'Dangal',
  'The Pianist',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Shawshank Redemption',
  "It's a Wonderful Life",
  'The Lord of the rings',
  'Harry Potter 1',
  'Se7en',
  'Black Panther',
  '2001: A Space Odyssey',
  'Vertigo ',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Pulp Fiction',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Saaho',
  'The Lord of the Rings: The Fellowship of the Ring',
  "Schindler's List",
  'Se7en',
  'The Intouchables',
  'Braveheart',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['inception',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Dark Knight',
  'The Intouchables',
  "One Flew Over the Cuckoo's Nest",
  'Star Wars: Episode VI - Return of the Jedi',
  'Once Upon a Time in the West',
  'Back to the Future',
  'Harry Potter 2',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Matrix',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'Pulp Fiction',
  'Prision Break',
  'The Silence of the Lambs',
  'The Lord of the Rings: The Return of the King',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Billa',
  'The Lord of the Rings: The Fellowship of the Ring',
  'Terminator 2: Judgment Day',
  'The Dark Knight',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Interstellar',
  'The Wolf of Wall Street',
  'Game of thrones',
  'Django Unchained',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'The Silence of the Lambs',
  'Se7en',
  'Pulp Fiction',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather: Part II',
  'The Lord of the Rings: The Return of the King',
  'Princess Mononoke',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Billa',
  'Alien',
  'The Silence of the Lambs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Good, the Bad and the Ugly',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Goodfellas',
  'The Lord of the Rings: The Fellowship of the Ring',
  'Once Upon a Time in the West',
  'Harry Potter 2',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["One Flew Over the Cuckoo's Nest",
  'The Lord of the Rings: The Return of the King',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Two Towers',
  'inception',
  'The Dark Knight',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'Casablanca',
  'Toy Story',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Goodfellas',
  'Parasite',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Fellowship of the Ring',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Seven Samurai',
  'Billa',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Dark Knight',
  'Black Panther',
  'whole wheat Star Wars: Episode V - The Empire Strikes Back',
  'Back to the Future',
  'Harry Potter 2',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Fellowship of the Ring',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["Schindler's List",
  'Fight Club',
  'Apocalypse Now',
  'The Matrix',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Harry Potter 2',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["Schindler's List",
  'Se7en',
  'The Lord of the Rings: The Return of the King',
  'Apocalypse Now',
  'Capernaum',
  'Dangal',
  'The Pianist',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'Prision Break',
  'Once Upon a Time in America',
  'Life Is Beautiful',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'Grave of the Fireflies ',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Se7en',
  'Hara-Kiri',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Shawshank Redemption',
  'Star Wars: Episode VI - Return of the Jedi',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Fellowship of the Ring',
  'The Silence of the Lambs',
  'Capernaum',
  '2001: A Space Odyssey',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Seven Samurai',
  'The Dark Knight',
  'Pulp Fiction',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Fellowship of the Ring',
  'Hara-Kiri',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Fellowship of the Ring',
  'The Silence of the Lambs',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Return of the King',
  'Harry Potter 2',
  'Parasite',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Wolf of Wall Street',
  'psycho',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather: Part II',
  'Seven Samurai',
  'Billa',
  'The Lion King',
  'inception',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Dark Knight',
  'The Silence of the Lambs',
  "Schindler's List",
  'The Intouchables',
  'Comedy nights with Kapil',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Pulp Fiction',
  'The Good, the Bad and the Ugly',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["Schindler's List",
  'Prision Break',
  'The Dark Knight Rises',
  'coco',
  'Dangal',
  'City of God',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather: Part II',
  'Billa',
  'The Dark Knight',
  'Joker',
  'The Departed',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Fellowship of the Ring',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Life Is Beautiful',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['City of God',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["Schindler's List",
  'Grave of the Fireflies ',
  'American History X',
  'The Lives of Others',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Godfather: Part II',
  'Pulp Fiction',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the Rings: The Return of the King',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Silence of the Lambs',
  'The Intouchables',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Interstellar',
  'Kanan Gill Comedy',
  'inception',
  'The Dark Knight',
  'Se7en',
  'Joker',
  'whole wheat Star Wars: Episode V - The Empire Strikes Back',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Good, the Bad and the Ugly',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Lord of the rings',
  'Harry Potter 1',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["It's a Wonderful Life",
  'Interstellar',
  'The Lion King',
  'The Wolf of Wall Street',
  'American Beauty ',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Shawshank Redemption',
  'Harry Potter 2',
  'American History X',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Good, the Bad and the Ugly',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Star Wars: Episode IV - A New Hope',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["Schindler's List",
  'Pulp Fiction',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Good, the Bad and the Ugly',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  'The Silence of the Lambs',
  '12 Angry Men',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Pulp Fiction',
  'Princess Mononoke',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["It's a Wonderful Life",
  'inception',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Dark Knight',
  '2001: A Space Odyssey',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Green Mile',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['Pulp Fiction',
  'Casablanca',
  'The Lord of the Rings: The Return of the King',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Shawshank Redemption',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Intouchables',
  'The Lord of the Rings: The Return of the King',
  'Whiplash',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Dark Knight',
  "One Flew Over the Cuckoo's Nest",
  'Modern Times',
  'The Lord of the Rings: The Return of the King',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ['The Shawshank Redemption',
  "It's a Wonderful Life",
  'Interstellar',
  'The Dark Knight',
  'Pulp Fiction',
  'The Departed',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["One Flew Over the Cuckoo's Nest",
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan',
  'nan'],
 ["One Flew Over the Cuckoo's Nest",
  'City of God',
  'nan',

In [13]:
from apyori import apriori
netflix = apriori(transactions=transactions, min_support = 0.003,min_confidence=0.2,min_lift = 3,min_len = 2)

In [14]:
netflix

#Visualizing

In [15]:
results = list(netflix)

In [16]:
results

[RelationRecord(items=frozenset({'Black Panther', 'Captain America'}), support=0.00334851326011251, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Captain America'}), items_add=frozenset({'Black Panther'}), confidence=0.24509803921568626, lift=5.154653410660038)]),
 RelationRecord(items=frozenset({'Game of thrones', 'Comedy nights with Kapil'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.20512820512820512, lift=3.1064648671139543)]),
 RelationRecord(items=frozenset({'Comedy nights with Kapil', 'Kanan Gill Comedy'}), support=0.008036431824270024, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Kanan Gill Comedy'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.2714932126696833, lift=4.111497618239058)]),
 RelationRecord(items=frozenset({'Game of thrones', 'Prision Break'}), support=0.004553978033753014, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Prision Break'}), confidence=0.2905982905982906, lift=4.832086498010774)]),
 RelationRecord(items=frozenset({'Harry Potter 2', 'Harry Potter 1'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Harry Potter 1'}), items_add=frozenset({'Harry Potter 2'}), confidence=0.36752136752136755, lift=4.642833383950135)]),
 RelationRecord(items=frozenset({'The Lord of the rings', 'Harry Potter 1'}), support=0.005089740155371015, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Harry Potter 1'}), items_add=frozenset({'The Lord of the rings'}), confidence=0.3247863247863248, lift=4.532438693186357)]),
 RelationRecord(items=frozenset({'Harry Potter 2', 'crimes of grindelwald'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'crimes of grindelwald'}), items_add=frozenset({'Harry Potter 2'}), confidence=0.3006993006993007, lift=3.7986818595955647)]),
 RelationRecord(items=frozenset({'Interstellar', 'inception'}), support=0.015938923118135547, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar'}), items_add=frozenset({'inception'}), confidence=0.3216216216216216, lift=3.262536721504113)]),
 RelationRecord(items=frozenset({'inception', 'The Wolf of Wall Street'}), support=0.005357621216180016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Wolf of Wall Street'}), items_add=frozenset({'inception'}), confidence=0.3773584905660377, lift=3.8279327317473335)]),
 RelationRecord(items=frozenset({'Back to the Future', 'Billa', 'The Lord of the rings'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Back to the Future', 'Billa'}), items_add=frozenset({'The Lord of the rings'}), confidence=0.2608695652173913, lift=3.6404713531084925), OrderedStatistic(items_base=frozenset({'Back to the Future', 'The Lord of the rings'}), items_add=frozenset({'Billa'}), confidence=0.33802816901408445, lift=3.5296759578449715)]),
 RelationRecord(items=frozenset({'The Intouchables', 'Back to the Future', 'Prision Break'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Back to the Future', 'Prision Break'}), items_add=frozenset({'The Intouchables'}), confidence=0.41379310344827586, lift=3.1882139425643214)]),
 RelationRecord(items=frozenset({'The Lion King', 'Billa', 'Casablanca'}), support=0.0030806321993035093, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa', 'Casablanca'}), items_add=frozenset({'The Lion King'}), confidence=0.2987012987012987, lift=4.347181084023189), OrderedStatistic(items_base=frozenset({'The Lion King', 'Casablanca'}), items_add=frozenset({'Billa'}), confidence=0.36507936507936506, lift=3.812143412143412)]),
 RelationRecord(items=frozenset({'The Intouchables', 'Comedy nights with Kapil', 'Billa'}), support=0.004821859094562015, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Comedy nights with Kapil', 'Billa'}), items_add=frozenset({'The Intouchables'}), confidence=0.42352941176470593, lift=3.2632307412128942), OrderedStatistic(items_base=frozenset({'The Intouchables', 'Billa'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.20338983050847462, lift=3.080138893663837)]),
 RelationRecord(items=frozenset({'Comedy nights with Kapil', 'Billa', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.2057416267942584, lift=3.115754534778769)]),
 RelationRecord(items=frozenset({'The Intouchables', 'Billa', "Schindler's List"}), support=0.004018215912135012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa', "Schindler's List"}), items_add=frozenset({'The Intouchables'}), confidence=0.5, lift=3.8524251805985554)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'The Lord of the rings', 'Billa'}), support=0.007232788641843022, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Dark Knight', 'The Lord of the rings'}), items_add=frozenset({'Billa'}), confidence=0.3068181818181818, lift=3.203782581055308)]),
 RelationRecord(items=frozenset({'The Intouchables', 'The Lion King', 'Billa'}), support=0.004152156442539513, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Intouchables', 'The Lion King'}), items_add=frozenset({'Billa'}), confidence=0.29523809523809524, lift=3.082863802863803)]),
 RelationRecord(items=frozenset({'The Lion King', 'Billa', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.00669702652022502, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'The Lion King'}), confidence=0.23923444976076555, lift=3.4817239803389386), OrderedStatistic(items_base=frozenset({'The Lion King', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'Billa'}), confidence=0.3184713375796178, lift=3.325464344572625)]),
 RelationRecord(items=frozenset({'The Lion King', 'The Lord of the rings', 'Billa'}), support=0.004018215912135012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Lion King', 'Billa'}), items_add=frozenset({'The Lord of the rings'}), confidence=0.24793388429752067, lift=3.4599521124584847), OrderedStatistic(items_base=frozenset({'The Lord of the rings', 'Billa'}), items_add=frozenset({'The Lion King'}), confidence=0.24, lift=3.492865497076023), OrderedStatistic(items_base=frozenset({'The Lord of the rings', 'The Lion King'}), items_add=frozenset({'Billa'}), confidence=0.35714285714285715, lift=3.7292707292707292)]),
 RelationRecord(items=frozenset({'The Lion King', 'Billa', 'Whiplash'}), support=0.00334851326011251, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa', 'Whiplash'}), items_add=frozenset({'The Lion King'}), confidence=0.23148148148148148, lift=3.3688903328279545)]),
 RelationRecord(items=frozenset({'The Lord of the rings', 'Billa', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.006027323868202518, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'The Lord of the rings'}), confidence=0.215311004784689, lift=3.0046952555560527)]),
 RelationRecord(items=frozenset({'inception', 'Billa', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.008706134476292525, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Billa', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'inception'}), confidence=0.3110047846889952, lift=3.1548392968587473)]),
 RelationRecord(items=frozenset({'The Silence of the Lambs', 'The Lord of the rings', 'Billa'}), support=0.005357621216180016, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Silence of the Lambs', 'Billa'}), items_add=frozenset({'The Lord of the rings'}), confidence=0.2325581395348837, lift=3.245381438817648), OrderedStatistic(items_base=frozenset({'The Silence of the Lambs', 'The Lord of the rings'}), items_add=frozenset({'Billa'}), confidence=0.2962962962962963, lift=3.093913493913494)]),
 RelationRecord(items=frozenset({'Black Panther', 'nan', 'Captain America'}), support=0.00334851326011251, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Captain America'}), items_add=frozenset({'Black Panther', 'nan'}), confidence=0.24509803921568626, lift=5.154653410660038), OrderedStatistic(items_base=frozenset({'nan', 'Captain America'}), items_add=frozenset({'Black Panther'}), confidence=0.24509803921568626, lift=5.154653410660038)]),
 RelationRecord(items=frozenset({'The Intouchables', 'The Shawshank Redemption', 'Casablanca'}), support=0.003750334851326011, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Intouchables', 'Casablanca'}), items_add=frozenset({'The Shawshank Redemption'}), confidence=0.27999999999999997, lift=3.201347626339969)]),
 RelationRecord(items=frozenset({'Game of thrones', 'Comedy nights with Kapil', 'nan'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'Comedy nights with Kapil', 'nan'}), confidence=0.20512820512820512, lift=3.1064648671139543), OrderedStatistic(items_base=frozenset({'Game of thrones', 'nan'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.20512820512820512, lift=3.1064648671139543)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'Comedy nights with Kapil', 'Kanan Gill Comedy'}), support=0.0038842753817305118, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Dark Knight', 'Kanan Gill Comedy'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.40277777777777773, lift=6.099673202614379)]),
 RelationRecord(items=frozenset({'Comedy nights with Kapil', 'nan', 'Kanan Gill Comedy'}), support=0.008036431824270024, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Kanan Gill Comedy'}), items_add=frozenset({'Comedy nights with Kapil', 'nan'}), confidence=0.2714932126696833, lift=4.111497618239058), OrderedStatistic(items_base=frozenset({'nan', 'Kanan Gill Comedy'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.2714932126696833, lift=4.111497618239058)]),
 RelationRecord(items=frozenset({'The Intouchables', 'Comedy nights with Kapil', 'Prision Break'}), support=0.003616394320921511, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Comedy nights with Kapil', 'Prision Break'}), items_add=frozenset({'The Intouchables'}), confidence=0.5, lift=3.8524251805985554), OrderedStatistic(items_base=frozenset({'The Intouchables', 'Comedy nights with Kapil'}), items_add=frozenset({'Prision Break'}), confidence=0.2109375, lift=3.507481904231626), OrderedStatistic(items_base=frozenset({'The Intouchables', 'Prision Break'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.24324324324324326, lift=3.6836796228276962)]),
 RelationRecord(items=frozenset({'Comedy nights with Kapil', 'The Lord of the Rings: The Fellowship of the Ring', 'Prision Break'}), support=0.0034824537905170103, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Lord of the Rings: The Fellowship of the Ring', 'Prision Break'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.2015503875968992, lift=3.0522823403619666)]),
 RelationRecord(items=frozenset({'The Dark Knight', 'Comedy nights with Kapil', "Schindler's List"}), support=0.005223680685775516, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Dark Knight', "Schindler's List"}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.22674418604651161, lift=3.4338176329072123)]),
 RelationRecord(items=frozenset({'The Intouchables', 'Comedy nights with Kapil', "Schindler's List"}), support=0.003616394320921511, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Comedy nights with Kapil', "Schindler's List"}), items_add=frozenset({'The Intouchables'}), confidence=0.40298507462686567, lift=3.1049396977958508), OrderedStatistic(items_base=frozenset({'The Intouchables', 'Comedy nights with Kapil'}), items_add=frozenset({"Schindler's List"}), confidence=0.2109375, lift=4.1773458222811675), OrderedStatistic(items_base=frozenset({'The Intouchables', "Schindler's List"}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.2368421052631579, lift=3.586740685384862)]),
 RelationRecord(items=frozenset({'The Intouchables', 'Comedy nights with Kapil', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.007232788641843022, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Intouchables', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.2030075187969925, lift=3.0743491589013106)]),
 RelationRecord(items=frozenset({'The Intouchables', 'Comedy nights with Kapil', 'The Lord of the rings'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Comedy nights with Kapil', 'The Lord of the rings'}), items_add=frozenset({'The Intouchables'}), confidence=0.39999999999999997, lift=3.081940144478844)]),
 RelationRecord(items=frozenset({'The Intouchables', 'inception', 'Comedy nights with Kapil'}), support=0.004955799624966515, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Intouchables', 'inception'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.22424242424242424, lift=3.395930911549573)]),
 RelationRecord(items=frozenset({'Comedy nights with Kapil', 'The Lion King', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.004420037503348513, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Comedy nights with Kapil', 'The Lion King'}), items_add=frozenset({'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.611111111111111, lift=3.496211153682418), OrderedStatistic(items_base=frozenset({'The Lion King', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.21019108280254775, lift=3.183137168770429)]),
 RelationRecord(items=frozenset({'Comedy nights with Kapil', 'The Pianist', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.005089740155371015, ordered_statistics=[OrderedStatistic(items_base=frozenset({'The Pianist', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'Comedy nights with Kapil'}), confidence=0.20105820105820105, lift=3.0448286594331218)]),
 RelationRecord(items=frozenset({'Game of thrones', 'nan', 'Prision Break'}), support=0.004553978033753014, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'nan', 'Prision Break'}), confidence=0.2905982905982906, lift=4.832086498010774), OrderedStatistic(items_base=frozenset({'Game of thrones', 'nan'}), items_add=frozenset({'Prision Break'}), confidence=0.2905982905982906, lift=4.832086498010774)]),
 RelationRecord(items=frozenset({'Game of thrones', 'The Lord of the Rings: The Fellowship of the Ring', 'The Dark Knight'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Game of thrones'}), items_add=frozenset({'The Dark Knight', 'The Lord of the Rings: The Fellowship of the Ring'}), confidence=0.20512820512820512, lift=3.42614581540756)]),
 RelationRecord(items=frozenset({'inception', 'Gladiator', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.00334851326011251, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Gladiator', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'inception'}), confidence=0.3378378378378379, lift=3.42703437132785)]),
 RelationRecord(items=frozenset({'Harry Potter 2', 'nan', 'Harry Potter 1'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Harry Potter 1'}), items_add=frozenset({'Harry Potter 2', 'nan'}), confidence=0.36752136752136755, lift=4.642833383950135), OrderedStatistic(items_base=frozenset({'nan', 'Harry Potter 1'}), items_add=frozenset({'Harry Potter 2'}), confidence=0.36752136752136755, lift=4.642833383950135)]),
 RelationRecord(items=frozenset({'nan', 'The Lord of the rings', 'Harry Potter 1'}), support=0.005089740155371015, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Harry Potter 1'}), items_add=frozenset({'The Lord of the rings', 'nan'}), confidence=0.3247863247863248, lift=4.532438693186357), OrderedStatistic(items_base=frozenset({'nan', 'Harry Potter 1'}), items_add=frozenset({'The Lord of the rings'}), confidence=0.3247863247863248, lift=4.532438693186357)]),
 RelationRecord(items=frozenset({'Harry Potter 2', 'crimes of grindelwald', 'nan'}), support=0.0057594428073935175, ordered_statistics=[OrderedStatistic(items_base=frozenset({'crimes of grindelwald'}), items_add=frozenset({'Harry Potter 2', 'nan'}), confidence=0.3006993006993007, lift=3.7986818595955647), OrderedStatistic(items_base=frozenset({'crimes of grindelwald', 'nan'}), items_add=frozenset({'Harry Potter 2'}), confidence=0.3006993006993007, lift=3.7986818595955647)]),
 RelationRecord(items=frozenset({'Interstellar', 'inception', 'Pulp Fiction'}), support=0.004152156442539513, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar', 'Pulp Fiction'}), items_add=frozenset({'inception'}), confidence=0.32978723404255317, lift=3.345368871415356), OrderedStatistic(items_base=frozenset({'inception', 'Pulp Fiction'}), items_add=frozenset({'Interstellar'}), confidence=0.20666666666666667, lift=4.170198198198198)]),
 RelationRecord(items=frozenset({'Interstellar', 'inception', 'The Dark Knight'}), support=0.00669702652022502, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar', 'The Dark Knight'}), items_add=frozenset({'inception'}), confidence=0.390625, lift=3.962508491847826)]),
 RelationRecord(items=frozenset({'Interstellar', 'The Intouchables', 'inception'}), support=0.003616394320921511, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar', 'The Intouchables'}), items_add=frozenset({'inception'}), confidence=0.391304347826087, lift=3.969399810964083)]),
 RelationRecord(items=frozenset({'Interstellar', 'inception', 'The Lord of the Rings: The Fellowship of the Ring'}), support=0.006429145459416019, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar', 'The Lord of the Rings: The Fellowship of the Ring'}), items_add=frozenset({'inception'}), confidence=0.39344262295081966, lift=3.9910905203136138)]),
 RelationRecord(items=frozenset({'Interstellar', 'inception', 'The Lord of the Rings: The Return of the King'}), support=0.0032145727297080095, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar', 'The Lord of the Rings: The Return of the King'}), items_add=frozenset({'inception'}), confidence=0.4615384615384615, lift=4.681856187290969), OrderedStatistic(items_base=frozenset({'inception', 'The Lord of the Rings: The Return of the King'}), items_add=frozenset({'Interstellar'}), confidence=0.23076923076923075, lift=4.656548856548856)]),
 RelationRecord(items=frozenset({'Interstellar', 'inception', 'The Silence of the Lambs'}), support=0.004018215912135012, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Interstellar', 'The Silence of the Lambs'}), items_add=frozenset({'inception'}), confidence=0.4411764705882353, lift=4.475303708439897)]),

#displaying results in proper way

In [20]:
def inspect(results):
  lhs = [tuple(result[2][0][0])[0] for result in results]
  rhs = [tuple(result[2][0][1])[0] for result in results]

  supports = [result[1] for result in results]
  return list(zip(lhs,rhs,supports))

In [21]:
resultdata = pd.DataFrame(inspect(results),columns=['movie1','movie2','support'])

In [22]:
resultdata

                movie1                    movie2   support
0      Captain America             Black Panther  0.003349
1      Game of thrones  Comedy nights with Kapil  0.003215
2    Kanan Gill Comedy  Comedy nights with Kapil  0.008036
3      Game of thrones             Prision Break  0.004554
4       Harry Potter 1            Harry Potter 2  0.005759
..                 ...                       ...       ...
155          inception  The Silence of the Lambs  0.004018
156   The Intouchables           The Dark Knight  0.003349
157          inception           The Dark Knight  0.003081
158    The Dark Knight     The Lord of the rings  0.003482
159          inception           The Dark Knight  0.003081

[160 rows x 3 columns]

from matplotlib import pyplot as plt
resultdata['support'].plot(kind='hist', bins=20, title='support')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
resultdata['support'].plot(kind='line', figsize=(8, 4), title='support')
plt.gca().spines[['top', 'right']].set_visible(False)

In [23]:
resultdata.nlargest(n = 30,columns='support')

,movie1,movie2,support
7,Interstellar,inception,0.015939
49,Interstellar,inception,0.015939
21,Billa,inception,0.008706
93,Billa,inception,0.008706
2,Kanan Gill Comedy,Comedy nights with Kapil,0.008036
27,Kanan Gill Comedy,Comedy nights with Kapil,0.008036
15,The Dark Knight,Billa,0.007233
32,The Intouchables,Comedy nights with Kapil,0.007233
83,The Dark Knight,Billa,0.007233
104,The Intouchables,Comedy nights with Kapil,0.007233
17,Billa,The Lion King,0.006697
44,Interstellar,inception,0.006697
88,Billa,The Lion King,0.006697
112,Interstellar,inception,0.006697
46,Interstellar,inception,0.006429
114,Interstellar,inception,0.006429
20,Billa,The Lord of the rings,0.006027
91,Billa,The Lord of the rings,0.006027
4,Harry Potter 1,Harry Potter 2,0.005759
6,crimes of grindelwald,Harry Potter 2,0.005759
13,Billa,Comedy nights with Kapil,0.005759
40,Harry Potter 1,Harry Potter 2,0.005759
42,crimes of grindelwald,Harry Potter 2,0.005759
72,Billa,Comedy nights with Kapil,0.005759
8,The Wolf of Wall Street,inception,0.005358
22,The Silence of the Lambs,The Lord of the rings,0.005358
50,The Lord of the Rings: The Fellowship of the Ring,inception,0.005358
65,The Wolf of Wall Street,inception,0.005358
94,The Silence of the Lambs,The Lord of the rings,0.005358
117,The Lord of the Rings: The Fellowship of the Ring,inception,0.005358